#!/bin/bash

cache_host=`relation-get private-address`
cache_port=`relation-get port`

# write out CACHE_BACKEND to local_settings.py?
cache_backend="memcached://$cache_host:$cache_port/"


service_hostname=`config-get service-hostname`
project_dir="/srv/$service_hostname/project"
echo "CACHE_BACKEND = \"$cache_backend\"" > $project_dir/cache-config.py

