#!/bin/bash

cache_host=`relation-get private-address`
cache_port=`relation-get port`

# write out CACHE_BACKEND to local_settings.py?
#cache_backend="memcached://$cache_host:$cache_port/?timeout=86400"

service_hostname=`config-get service-hostname`
project_dir="/srv/$service_hostname"
project_location=`config-get app-source-project-location`

mkdir -p $project_dir/$project_location

cat > $project_dir/$project_location/cache_config.py << EOS
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '$cache_host:$cache_port',
        'TIMEOUT': 86400,
    }
}
EOS


