#!/bin/bash

database_user=`relation-get user`
database_password=`relation-get password`
database_host=`relation-get host`
database_name=`relation-get database`
database_port="5432"
secret_key=`cat $CHARM_DIR/SECRET_KEY`
# All values are set together, so checking on a single value is enough
# If $user is not set, DB is still setting itself up, we exit awaiting next run
[ -z "$database_user" ] && exit 0

service_hostname=`config-get service-hostname`
site_root="http://$service_hostname"
theme_media="/srv/$service_hostname/project/media"

FACTER_database_user=$database_user \
FACTER_database_password=$database_password \
FACTER_database_host=$database_host \
FACTER_database_name=$database_name \
FACTER_database_port=$database_port \
FACTER_service_hostname=$service_hostname \
FACTER_secret_key=$secret_key \
FACTER_site_root=$site_root \
FACTER_theme_media=$theme_media \
puppet apply $PWD/manifests/database_settings.pp

remove_south() {
  local project_dir="/srv/$service_hostname/project"
  local settings_file="$project_dir/settings.py"
  sed -i "s/\('south',\)/#\1/" $settings_file
}
remove_south

configure_database() {
  local project_dir="/srv/$service_hostname/project"
  cd $project_dir && python ./manage.py init-summit --settings=ubuntu_settings
  cd $project_dir && python ./manage.py pullapps --settings=ubuntu_settings
  cd $project_dir && python ./manage.py syncdb --noinput --settings=ubuntu_settings
}
configure_database

open-port 80/tcp

service apache2 restart

